var DB2 = {
    "spirits" :
   [{
        "nr": "7845701",
        "artikelid": "889891",
        "varnummer": "78457",
        "namn": "Musmeci",
        "namn2": "Etna Bianco",
        "prisinklmoms": "242.00",
        "volymiml": null,
        "prisperliter": null,
        "saljstart": "2014-10-01",
        "slutlev": " ",
        "varugrupp": "Vitt vin",
        "forpackning": "Flaska",
        "forslutning": "",
        "ursprung": "Sicilien, Etna",
        "ursprunglandnamn": "Italien",
        "producent": "Tenuta di Fessina",
        "leverantor": "Handpicked Wines Sweden AB",
        "argang": "2012",
        "provadargang": "",
        "alkoholhalt": "13.5%",
        "modul": "",
        "sortiment": "BS",
        "ekologisk": "0",
        "koscher": "0"
    }, {
        "nr": "7845801",
        "artikelid": "889900",
        "varnummer": "78458",
        "namn": "Musmeci",
        "namn2": "Etna Rosso",
        "prisinklmoms": "374.00",
        "volymiml": null,
        "prisperliter": null,
        "saljstart": "2014-10-01",
        "slutlev": " ",
        "varugrupp": "Rött vin",
        "forpackning": "Flaska",
        "forslutning": "",
        "ursprung": "Sicilien, Etna",
        "ursprunglandnamn": "Italien",
        "producent": "Tenuta di Fessina",
        "leverantor": "Handpicked Wines Sweden AB",
        "argang": "2010",
        "provadargang": "",
        "alkoholhalt": "13.5%",
        "modul": "",
        "sortiment": "BS",
        "ekologisk": "0",
        "koscher": "0"
    }, {
        "nr": "7845901",
        "artikelid": "889924",
        "varnummer": "78459",
        "namn": "Wildwux",
        "namn2": "Gröner Veltliner",
        "prisinklmoms": "149.00",
        "volymiml": null,
        "prisperliter": null,
        "saljstart": "2014-10-01",
        "slutlev": " ",
        "varugrupp": "Vitt vin",
        "forpackning": "Flaska",
        "forslutning": "",
        "ursprung": "Nieder österreich, Kremstal",
        "ursprunglandnamn": "Österrike",
        "producent": "Geyerhof",
        "leverantor": "Handpicked Wines Sweden AB",
        "argang": "2013",
        "provadargang": "",
        "alkoholhalt": "12.5%",
        "modul": "",
        "sortiment": "BS",
        "ekologisk": "1",
        "koscher": "0"
    }, {
        "nr": "7846001",
        "artikelid": "889931",
        "varnummer": "78460",
        "namn": "Manzoni",
        "namn2": "Bianco",
        "prisinklmoms": "145.00",
        "volymiml": null,
        "prisperliter": null,
        "saljstart": "2014-10-01",
        "slutlev": " ",
        "varugrupp": "Vitt vin",
        "forpackning": "Flaska",
        "forslutning": "",
        "ursprung": "Trentino-Alto Adige, Trentino, Vigneti d",
        "ursprunglandnamn": "Italien",
        "producent": "Azienda Agricola Cesconi Paolo",
        "leverantor": "Handpicked Wines Sweden AB",
        "argang": "2013",
        "provadargang": "",
        "alkoholhalt": "13%",
        "modul": "",
        "sortiment": "BS",
        "ekologisk": "0",
        "koscher": "0"
    }, {
        "nr": "7846101",
        "artikelid": "889944",
        "varnummer": "78461",
        "namn": "Moratel Rosso",
        "namn2": "",
        "prisinklmoms": "162.00",
        "volymiml": null,
        "prisperliter": null,
        "saljstart": "2014-10-01",
        "slutlev": " ",
        "varugrupp": "Vitt vin",
        "forpackning": "Flaska",
        "forslutning": "",
        "ursprung": "Trentino-Alto Adige, Trentino, Vigneti d",
        "ursprunglandnamn": "Italien",
        "producent": "Azienda Agricola Cesconi Paolo",
        "leverantor": "Handpicked Wines Sweden AB",
        "argang": "2011",
        "provadargang": "",
        "alkoholhalt": "13.5%",
        "modul": "",
        "sortiment": "BS",
        "ekologisk": "0",
        "koscher": "0"
    }, {
        "nr": "7846401",
        "artikelid": "890003",
        "varnummer": "78464",
        "namn": "Sprinzenberg",
        "namn2": "Riesling",
        "prisinklmoms": "162.00",
        "volymiml": null,
        "prisperliter": null,
        "saljstart": "2014-10-01",
        "slutlev": " ",
        "varugrupp": "Vitt vin",
        "forpackning": "Flaska",
        "forslutning": "",
        "ursprung": "Nieder österreich, Kremstal",
        "ursprunglandnamn": "Österrike",
        "producent": "Geyerhof",
        "leverantor": "Handpicked Wines Sweden AB",
        "argang": "2013",
        "provadargang": "",
        "alkoholhalt": "12%",
        "modul": "",
        "sortiment": "BS",
        "ekologisk": "1",
        "koscher": "0"
    }, {
        "nr": "7846502",
        "artikelid": "890010",
        "varnummer": "78465",
        "namn": "Corte Sant Alda",
        "namn2": "Recioto Della Valpolicella",
        "prisinklmoms": "339.00",
        "volymiml": null,
        "prisperliter": null,
        "saljstart": "2014-10-01",
        "slutlev": " ",
        "varugrupp": "Rött vin",
        "forpackning": "Flaska",
        "forslutning": "",
        "ursprung": "Venetien, Valpolicella, Recioto della Va",
        "ursprunglandnamn": "Italien",
        "producent": "Corte Sant'Alda",
        "leverantor": "Vinovativa AB",
        "argang": "2011",
        "provadargang": "",
        "alkoholhalt": "15%",
        "modul": "",
        "sortiment": "BS",
        "ekologisk": "1",
        "koscher": "0"
    }, {
        "nr": "7846601",
        "artikelid": "890096",
        "varnummer": "78466",
        "namn": "Corte Sant Alda",
        "namn2": "Amarone Della Valpolicella",
        "prisinklmoms": "529.00",
        "volymiml": null,
        "prisperliter": null,
        "saljstart": "2014-10-01",
        "slutlev": " ",
        "varugrupp": "Rött vin",
        "forpackning": "Flaska",
        "forslutning": "",
        "ursprung": "Venetien, Valpolicella, Amarone della Va",
        "ursprunglandnamn": "Italien",
        "producent": "Corte Sant'Alda",
        "leverantor": "Vinovativa AB",
        "argang": "2009",
        "provadargang": "",
        "alkoholhalt": "15.5%",
        "modul": "",
        "sortiment": "BS",
        "ekologisk": "1",
        "koscher": "0"
    }, {
        "nr": "7846801",
        "artikelid": "890142",
        "varnummer": "78468",
        "namn": "Corte Sant Alda",
        "namn2": "Ca Fiui",
        "prisinklmoms": "149.00",
        "volymiml": null,
        "prisperliter": null,
        "saljstart": "2014-10-01",
        "slutlev": " ",
        "varugrupp": "Rött vin",
        "forpackning": "Flaska",
        "forslutning": "",
        "ursprung": "Venetien, Valpolicella",
        "ursprunglandnamn": "Italien",
        "producent": "Corte Sant' Alda",
        "leverantor": "Vinovativa AB",
        "argang": "2012",
        "provadargang": "",
        "alkoholhalt": "12.5%",
        "modul": "",
        "sortiment": "BS",
        "ekologisk": "1",
        "koscher": "0"
    }, {
        "nr": "7846901",
        "artikelid": "890171",
        "varnummer": "78469",
        "namn": "Corte Sant Alda",
        "namn2": "Campi Magri Ripasso",
        "prisinklmoms": "199.00",
        "volymiml": null,
        "prisperliter": null,
        "saljstart": "2014-10-01",
        "slutlev": " ",
        "varugrupp": "Rött vin",
        "forpackning": "Flaska",
        "forslutning": "",
        "ursprung": "Venetien, Valpolicella, Valpolicella Sup",
        "ursprunglandnamn": "Italien",
        "producent": "Corte Sant' Alda",
        "leverantor": "Vinovativa AB",
        "argang": "2010",
        "provadargang": "",
        "alkoholhalt": "13.5%",
        "modul": "",
        "sortiment": "BS",
        "ekologisk": "1",
        "koscher": "0"
    }, {
        "nr": "7847101",
        "artikelid": "890433",
        "varnummer": "78471",
        "namn": "Duemani",
        "namn2": "Cabernet Franc",
        "prisinklmoms": "719.00",
        "volymiml": null,
        "prisperliter": null,
        "saljstart": "2014-10-01",
        "slutlev": " ",
        "varugrupp": "RÖtt vin",
        "forpackning": "Flaska",
        "forslutning": "",
        "ursprung": "Toscana",
        "ursprunglandnamn": "Italien",
        "producent": "Duemani",
        "leverantor": "R&L Wines AB",
        "argang": "2010",
        "provadargang": "",
        "alkoholhalt": "14.5%",
        "modul": "",
        "sortiment": "BS",
        "ekologisk": "1",
        "koscher": "0"
    }, {
        "nr": "7847201",
        "artikelid": "890551",
        "varnummer": "78472",
        "namn": "Suisassi",
        "namn2": "Syrah",
        "prisinklmoms": "719.00",
        "volymiml": null,
        "prisperliter": null,
        "saljstart": "2014-10-01",
        "slutlev": " ",
        "varugrupp": "RÖtt vin",
        "forpackning": "Flaska",
        "forslutning": "",
        "ursprung": "Toscana",
        "ursprunglandnamn": "Italien",
        "producent": "Duemani",
        "leverantor": "R&L Wines AB",
        "argang": "2010",
        "provadargang": "",
        "alkoholhalt": "14.5%",
        "modul": "",
        "sortiment": "BS",
        "ekologisk": "1",
        "koscher": "0"
    }, {
        "nr": "7847301",
        "artikelid": "890574",
        "varnummer": "78473",
        "namn": "Altrovino",
        "namn2": "Merlot Cabernet Franc",
        "prisinklmoms": "289.00",
        "volymiml": null,
        "prisperliter": null,
        "saljstart": "2014-10-01",
        "slutlev": " ",
        "varugrupp": "RÖtt vin",
        "forpackning": "Flaska",
        "forslutning": "",
        "ursprung": "Toscana",
        "ursprunglandnamn": "Italien",
        "producent": "Duemani",
        "leverantor": "R&L Wines AB",
        "argang": "2011",
        "provadargang": "",
        "alkoholhalt": "14%",
        "modul": "",
        "sortiment": "BS",
        "ekologisk": "1",
        "koscher": "0"
    },
    {
        "nr": "8031401",
        "artikelid": "865823",
        "varnummer": "80314",
        "namn": "Amager No Rice And Curry",
        "namn2": "India Pale Lager",
        "prisinklmoms": "50.90",
        "volymiml": null,
        "prisperliter": null,
        "saljstart": "2014-07-01",
        "slutlev": " ",
        "varugrupp": "Öl, Ljus lager",
        "forpackning": "Flaska",
        "forslutning": "",
        "ursprung": "",
        "ursprunglandnamn": "Danmark",
        "producent": "Amager Bryghus",
        "leverantor": "Elixir HB",
        "argang": "",
        "provadargang": "",
        "alkoholhalt": "5%",
        "modul": "",
        "sortiment": "BS",
        "ekologisk": "0",
        "koscher": "0"
    },
    {
        "nr": "1106801",
        "artikelid": "730949",
        "varnummer": "11068",
        "namn": "The Sinner Series Greed",
        "namn2": "Amager",
        "prisinklmoms": "47.80",
        "volymiml": null,
        "prisperliter": null,
        "saljstart": "2013-03-01",
        "slutlev": " ",
        "varugrupp": "Öl, Ljus lager",
        "forpackning": "Flaska",
        "forslutning": "",
        "ursprung": "",
        "ursprunglandnamn": "Danmark",
        "producent": "Amager Bryghus",
        "leverantor": "Elixir HB",
        "argang": "",
        "provadargang": "",
        "alkoholhalt": "4.6%",
        "modul": "T5",
        "sortiment": "TSE",
        "ekologisk": "0",
        "koscher": "0"
    },
    {
        "nr": "1107503",
        "artikelid": "734813",
        "varnummer": "11075",
        "namn": "Abstrakt 12",
        "namn2": "",
        "prisinklmoms": "129.00",
        "volymiml": null,
        "prisperliter": null,
        "saljstart": "2013-03-01",
        "slutlev": " ",
        "varugrupp": "Öl, Ale",
        "forpackning": "Flaska",
        "forslutning": "",
        "ursprung": "Skottland",
        "ursprunglandnamn": "Storbritannien",
        "producent": "BrewDog",
        "leverantor": "Cask Sweden AB",
        "argang": "2012",
        "provadargang": "2012",
        "alkoholhalt": "11.7%",
        "modul": "T6",
        "sortiment": "TSE",
        "ekologisk": "0",
        "koscher": "0"
    },
    {
        "nr": "1107803",
        "artikelid": "735181",
        "varnummer": "11078",
        "namn": "Le Freak",
        "namn2": "Ale",
        "prisinklmoms": "44.90",
        "volymiml": null,
        "prisperliter": null,
        "saljstart": "2013-04-02",
        "slutlev": " ",
        "varugrupp": "Öl, Ale",
        "forpackning": "Flaska",
        "forslutning": "",
        "ursprung": "",
        "ursprunglandnamn": "USA",
        "producent": "Green Flash Brewing Co",
        "leverantor": "Brill & Co AB",
        "argang": "",
        "provadargang": "",
        "alkoholhalt": "9.2%",
        "modul": "",
        "sortiment": "TSE",
        "ekologisk": "0",
        "koscher": "0"
    },{
       "nr": "1004703",
       "artikelid": "723841",
       "varnummer": "10047",
       "namn": "Nils Oscar",
       "namn2": "Celebration Ale",
       "prisinklmoms": "43.70",
       "volymiml": null,
       "prisperliter": null,
       "saljstart": "2013-02-01",
       "slutlev": " ",
       "varugrupp": "Öl, Ale",
       "forpackning": "Flaska",
       "forslutning": "",
       "ursprung": "",
       "ursprunglandnamn": "Sverige",
       "producent": "Nils Oscar Company",
       "leverantor": "The Nils Oscar Company AB",
       "argang": "",
       "provadargang": "",
       "alkoholhalt": "9.4%",
       "modul": "T5",
       "sortiment": "TSE",
       "ekologisk": "0",
       "koscher": "0"
   },{
       "nr": "140615",
       "artikelid": "508224",
       "varnummer": "1406",
       "namn": "Anderssons",
       "namn2": "",
       "prisinklmoms": "8.90",
       "volymiml": null,
       "prisperliter": null,
       "saljstart": "2010-10-01",
       "slutlev": " ",
       "varugrupp": "Öl, Ljus lager",
       "forpackning": "Burk",
       "forslutning": "",
       "ursprung": "",
       "ursprunglandnamn": "Sverige",
       "producent": "Hellefors Bryggeri",
       "leverantor": "Anderssons Öl AB",
       "argang": "",
       "provadargang": "",
       "alkoholhalt": "5.2%",
       "modul": "",
       "sortiment": "FS",
       "ekologisk": "0",
       "koscher": "0"
   },{
       "nr": "140715",
       "artikelid": "675480",
       "varnummer": "1407",
       "namn": "Backyard Brew",
       "namn2": "The Lawn Mower",
       "prisinklmoms": "9.90",
       "volymiml": null,
       "prisperliter": null,
       "saljstart": "2012-10-01",
       "slutlev": " ",
       "varugrupp": "Öl, Ljus lager",
       "forpackning": "Burk",
       "forslutning": "",
       "ursprung": "Hallands län, Falkenbergs kommun",
       "ursprunglandnamn": "Sverige",
       "producent": "Carlsberg Sverige AB",
       "leverantor": "Carlsberg Sverige AB",
       "argang": "",
       "provadargang": "",
       "alkoholhalt": "4.8%",
       "modul": "",
       "sortiment": "BS",
       "ekologisk": "0",
       "koscher": "0"
   }]
};