var DB2 = {
    "spirits" :
            [
                {
                    "nr": "7845701",
                    "articleid": "889891",
                    "articletype": "78457",
                    "name": "Musmeci",
                    "name2": "Etna Bianco",
                    "priceinclvat": "242.00",
                    "volumeml": null,
                    "priceperlitre": null,
                    "introduced": "2014-10-01",
                    "finaldelivery": " ",
                    "catgegory": "Vitt vin",
                    "packaging": "Flaska",
                    "captype": "",
                    "countryoforigin": "Sicilien, Etna",
                    "countryoforiginlandname": "Italien",
                    "producer": "Tenuta di Fessina",
                    "provider": "Handpicked Wines Sweden AB",
                    "productionyear": "2012",
                    "testedproductionyear": "",
                    "alcoholstrength": "13.5%",
                    "module": "",
                    "assortment": "BS",
                    "organic": "0",
                    "kosher": "0"
                }, 
                {
                    "nr": "7845801",
                    "articleid": "889900",
                    "articletype": "78458",
                    "name": "Musmeci",
                    "name2": "Etna Rosso",
                    "priceinclvat": "374.00",
                    "volumeml": null,
                    "priceperlitre": null,
                    "introduced": "2014-10-01",
                    "finaldelivery": " ",
                    "catgegory": "R\u00c3\u00b6tt vin",
                    "packaging": "Flaska",
                    "captype": "",
                    "countryoforigin": "Sicilien, Etna",
                    "countryoforiginlandname": "Italien",
                    "producer": "Tenuta di Fessina",
                    "provider": "Handpicked Wines Sweden AB",
                    "productionyear": "2010",
                    "testedproductionyear": "",
                    "alcoholstrength": "13.5%",
                    "module": "",
                    "assortment": "BS",
                    "organic": "0",
                    "kosher": "0"
                }, 
                {
                    "nr": "7845901",
                    "articleid": "889924",
                    "articletype": "78459",
                    "name": "Wildwux",
                    "name2": "Gr\u00c3\u00bcner Veltliner",
                    "priceinclvat": "149.00",
                    "volumeml": null,
                    "priceperlitre": null,
                    "introduced": "2014-10-01",
                    "finaldelivery": " ",
                    "catgegory": "Vitt vin",
                    "packaging": "Flaska",
                    "captype": "",
                    "countryoforigin": "Nieder\u00c3\u00b6sterreich, Kremstal",
                    "countryoforiginlandname": "\u00c3\u2013sterrike",
                    "producer": "Geyerhof",
                    "provider": "Handpicked Wines Sweden AB",
                    "productionyear": "2013",
                    "testedproductionyear": "",
                    "alcoholstrength": "12.5%",
                    "module": "",
                    "assortment": "BS",
                    "organic": "1",
                    "kosher": "0"
                }, 
                {
                    "nr": "7846001",
                    "articleid": "889931",
                    "articletype": "78460",
                    "name": "Manzoni",
                    "name2": "Bianco",
                    "priceinclvat": "145.00",
                    "volumeml": null,
                    "priceperlitre": null,
                    "introduced": "2014-10-01",
                    "finaldelivery": " ",
                    "catgegory": "Vitt vin",
                    "packaging": "Flaska",
                    "captype": "",
                    "countryoforigin": "Trentino-Alto Adige, Trentino, Vigneti d",
                    "countryoforiginlandname": "Italien",
                    "producer": "Azienda Agricola Cesconi Paolo",
                    "provider": "Handpicked Wines Sweden AB",
                    "productionyear": "2013",
                    "testedproductionyear": "",
                    "alcoholstrength": "13%",
                    "module": "",
                    "assortment": "BS",
                    "organic": "0",
                    "kosher": "0"
                }, 
                {
                    "nr": "7846101",
                    "articleid": "889944",
                    "articletype": "78461",
                    "name": "Moratel Rosso",
                    "name2": "",
                    "priceinclvat": "162.00",
                    "volumeml": null,
                    "priceperlitre": null,
                    "introduced": "2014-10-01",
                    "finaldelivery": " ",
                    "catgegory": "R\u00c3\u00b6tt vin",
                    "packaging": "Flaska",
                    "captype": "",
                    "countryoforigin": "Trentino-Alto Adige, Trentino, Vigneti d",
                    "countryoforiginlandname": "Italien",
                    "producer": "Azienda Agricola Cesconi Paolo",
                    "provider": "Handpicked Wines Sweden AB",
                    "productionyear": "2011",
                    "testedproductionyear": "",
                    "alcoholstrength": "13.5%",
                    "module": "",
                    "assortment": "BS",
                    "organic": "0",
                    "kosher": "0"
                }, 
                {
                    "nr": "8890003",
                    "articleid": "785133",
                    "articletype": "88900",
                    "name": "Eskilstuna \u00c3\u2013lkultur",
                    "name2": "Modern Lager",
                    "priceinclvat": "25.20",
                    "volumeml": null,
                    "priceperlitre": null,
                    "introduced": "2013-09-02",
                    "finaldelivery": " ",
                    "catgegory": "\u00c3\u2013l, Ljus lager",
                    "packaging": "Flaska",
                    "captype": "",
                    "countryoforigin": "S\u00c3\u00b6dermanlands l\u00c3\u00a4n, Eskilstuna kommun",
                    "countryoforiginlandname": "Sverige",
                    "producer": "Eskilstuna \u00c3\u2013lkultur",
                    "provider": "Eskilstuna \u00c3\u2013lkultur AB",
                    "productionyear": "",
                    "testedproductionyear": "",
                    "alcoholstrength": "5.8%",
                    "module": "",
                    "assortment": "TSLS",
                    "organic": "0",
                    "kosher": "0"
                }, 
                {
                    "nr": "7846502",
                    "articleid": "890010",
                    "articletype": "78465",
                    "name": "Corte Sant Alda",
                    "name2": "Recioto Della Valpolicella",
                    "priceinclvat": "339.00",
                    "volumeml": null,
                    "priceperlitre": null,
                    "introduced": "2014-10-01",
                    "finaldelivery": " ",
                    "catgegory": "R\u00c3\u00b6tt vin",
                    "packaging": "Flaska",
                    "captype": "",
                    "countryoforigin": "Venetien, Valpolicella, Recioto della Va",
                    "countryoforiginlandname": "Italien",
                    "producer": "Corte Sant'Alda",
                    "provider": "Vinovativa AB",
                    "productionyear": "2011",
                    "testedproductionyear": "",
                    "alcoholstrength": "15%",
                    "module": "",
                    "assortment": "BS",
                    "organic": "1",
                    "kosher": "0"
                }, 
                {
                    "nr": "7846601",
                    "articleid": "890096",
                    "articletype": "78466",
                    "name": "Corte Sant Alda",
                    "name2": "Amarone Della Valpolicella",
                    "priceinclvat": "529.00",
                    "volumeml": null,
                    "priceperlitre": null,
                    "introduced": "2014-10-01",
                    "finaldelivery": " ",
                    "catgegory": "R\u00c3\u00b6tt vin",
                    "packaging": "Flaska",
                    "captype": "",
                    "countryoforigin": "Venetien, Valpolicella, Amarone della Va",
                    "countryoforiginlandname": "Italien",
                    "producer": "Corte Sant'Alda",
                    "provider": "Vinovativa AB",
                    "productionyear": "2009",
                    "testedproductionyear": "",
                    "alcoholstrength": "15.5%",
                    "module": "",
                    "assortment": "BS",
                    "organic": "1",
                    "kosher": "0"
                },
                {
                    "nr": "7846801",
                    "articleid": "890142",
                    "articletype": "78468",
                    "name": "Corte Sant Alda",
                    "name2": "Ca Fiui",
                    "priceinclvat": "149.00",
                    "volumeml": null,
                    "priceperlitre": null,
                    "introduced": "2014-10-01",
                    "finaldelivery": " ",
                    "catgegory": "R\u00c3\u00b6tt vin",
                    "packaging": "Flaska",
                    "captype": "",
                    "countryoforigin": "Venetien, Valpolicella",
                    "countryoforiginlandname": "Italien",
                    "producer": "Corte Sant' Alda",
                    "provider": "Vinovativa AB",
                    "productionyear": "2012",
                    "testedproductionyear": "",
                    "alcoholstrength": "12.5%",
                    "module": "",
                    "assortment": "BS",
                    "organic": "1",
                    "kosher": "0"
                }, 
                {
                    "nr": "7846901",
                    "articleid": "890171",
                    "articletype": "78469",
                    "name": "Corte Sant Alda",
                    "name2": "Campi Magri Ripasso",
                    "priceinclvat": "199.00",
                    "volumeml": null,
                    "priceperlitre": null,
                    "introduced": "2014-10-01",
                    "finaldelivery": " ",
                    "catgegory": "R\u00c3\u00b6tt vin",
                    "packaging": "Flaska",
                    "captype": "",
                    "countryoforigin": "Venetien, Valpolicella, Valpolicella Sup",
                    "countryoforiginlandname": "Italien",
                    "producer": "Corte Sant' Alda",
                    "provider": "Vinovativa AB",
                    "productionyear": "2010",
                    "testedproductionyear": "",
                    "alcoholstrength": "13.5%",
                    "module": "",
                    "assortment": "BS",
                    "organic": "1",
                    "kosher": "0"
                },
                {
                    "nr": "7847101",
                    "articleid": "890433",
                    "articletype": "78471",
                    "name": "Duemani",
                    "name2": "Cabernet Franc",
                    "priceinclvat": "719.00",
                    "volumeml": null,
                    "priceperlitre": null,
                    "introduced": "2014-10-01",
                    "finaldelivery": " ",
                    "catgegory": "R\u00c3\u00b6tt vin",
                    "packaging": "Flaska",
                    "captype": "",
                    "countryoforigin": "Toscana",
                    "countryoforiginlandname": "Italien",
                    "producer": "Duemani",
                    "provider": "R&L Wines AB",
                    "productionyear": "2010",
                    "testedproductionyear": "",
                    "alcoholstrength": "14.5%",
                    "module": "",
                    "assortment": "BS",
                    "organic": "1",
                    "kosher": "0"
                }, 
                {
                    "nr": "7847201",
                    "articleid": "890551",
                    "articletype": "78472",
                    "name": "Suisassi",
                    "name2": "Syrah",
                    "priceinclvat": "719.00",
                    "volumeml": null,
                    "priceperlitre": null,
                    "introduced": "2014-10-01",
                    "finaldelivery": " ",
                    "catgegory": "R\u00c3\u00b6tt vin",
                    "packaging": "Flaska",
                    "captype": "",
                    "countryoforigin": "Toscana",
                    "countryoforiginlandname": "Italien",
                    "producer": "Duemani",
                    "provider": "R&L Wines AB",
                    "productionyear": "2010",
                    "testedproductionyear": "",
                    "alcoholstrength": "14.5%",
                    "module": "",
                    "assortment": "BS",
                    "organic": "1",
                    "kosher": "0"
                }, 
                {
                    "nr": "7847301",
                    "articleid": "890574",
                    "articletype": "78473",
                    "name": "Altrovino",
                    "name2": "Merlot Cabernet Franc",
                    "priceinclvat": "289.00",
                    "volumeml": null,
                    "priceperlitre": null,
                    "introduced": "2014-10-01",
                    "finaldelivery": " ",
                    "catgegory": "R\u00c3\u00b6tt vin",
                    "packaging": "Flaska",
                    "captype": "",
                    "countryoforigin": "Toscana",
                    "countryoforiginlandname": "Italien",
                    "producer": "Duemani",
                    "provider": "R&L Wines AB",
                    "productionyear": "2011",
                    "testedproductionyear": "",
                    "alcoholstrength": "14%",
                    "module": "",
                    "assortment": "BS",
                    "organic": "1",
                    "kosher": "0"
                },
                {
                    "nr": "8031401",
                    "articleid": "865823",
                    "articletype": "80314",
                    "name": "Amager No Rice And Curry",
                    "name2": "India Pale Lager",
                    "priceinclvat": "50.90",
                    "volumeml": null,
                    "priceperlitre": null,
                    "introduced": "2014-07-01",
                    "finaldelivery": " ",
                    "catgegory": "\u00c3\u2013l, Ljus lager",
                    "packaging": "Flaska",
                    "captype": "",
                    "countryoforigin": "",
                    "countryoforiginlandname": "Danmark",
                    "producer": "Amager Bryghus",
                    "provider": "Elixir HB",
                    "productionyear": "",
                    "testedproductionyear": "",
                    "alcoholstrength": "5%",
                    "module": "",
                    "assortment": "BS",
                    "organic": "0",
                    "kosher": "0"
                },
                {
                    "nr": "1106801",
                    "articleid": "730949",
                    "articletype": "11068",
                    "name": "The Sinner Series Greed",
                    "name2": "Amager",
                    "priceinclvat": "47.80",
                    "volumeml": null,
                    "priceperlitre": null,
                    "introduced": "2013-03-01",
                    "finaldelivery": " ",
                    "catgegory": "\u00c3\u2013l, Ljus lager",
                    "packaging": "Flaska",
                    "captype": "",
                    "countryoforigin": "",
                    "countryoforiginlandname": "Danmark",
                    "producer": "Amager Bryghus",
                    "provider": "Elixir HB",
                    "productionyear": "",
                    "testedproductionyear": "",
                    "alcoholstrength": "4.6%",
                    "module": "T5",
                    "assortment": "TSE",
                    "organic": "0",
                    "kosher": "0"
                },
                {
                    "nr": "1107503",
                    "articleid": "734813",
                    "articletype": "11075",
                    "name": "Abstrakt 12",
                    "name2": "",
                    "priceinclvat": "129.00",
                    "volumeml": null,
                    "priceperlitre": null,
                    "introduced": "2013-03-01",
                    "finaldelivery": " ",
                    "catgegory": "\u00c3\u2013l, Ale",
                    "packaging": "Flaska",
                    "captype": "",
                    "countryoforigin": "Skottland",
                    "countryoforiginlandname": "Storbritannien",
                    "producer": "BrewDog",
                    "provider": "Cask Sweden AB",
                    "productionyear": "2012",
                    "testedproductionyear": "2012",
                    "alcoholstrength": "11.7%",
                    "module": "T6",
                    "assortment": "TSE",
                    "organic": "0",
                    "kosher": "0"
                },
                {
                    "nr": "1107803",
                    "articleid": "735181",
                    "articletype": "11078",
                    "name": "Le Freak",
                    "name2": "Ale",
                    "priceinclvat": "44.90",
                    "volumeml": null,
                    "priceperlitre": null,
                    "introduced": "2013-04-02",
                    "finaldelivery": " ",
                    "catgegory": "\u00c3\u2013l, Ale",
                    "packaging": "Flaska",
                    "captype": "",
                    "countryoforigin": "",
                    "countryoforiginlandname": "USA",
                    "producer": "Green Flash Brewing Co",
                    "provider": "Brill & Co AB",
                    "productionyear": "",
                    "testedproductionyear": "",
                    "alcoholstrength": "9.2%",
                    "module": "",
                    "assortment": "TSE",
                    "organic": "0",
                    "kosher": "0"
                    },{
                    "nr": "1004703",
                    "articleid": "723841",
                    "articletype": "10047",
                    "name": "Nils Oscar",
                    "name2": "Celebration Ale",
                    "priceinclvat": "43.70",
                    "volumeml": null,
                    "priceperlitre": null,
                    "introduced": "2013-02-01",
                    "finaldelivery": " ",
                    "catgegory": "\u00c3\u2013l, Ale",
                    "packaging": "Flaska",
                    "captype": "",
                    "countryoforigin": "",
                    "countryoforiginlandname": "Sverige",
                    "producer": "Nils Oscar Company",
                    "provider": "The Nils Oscar Company AB",
                    "productionyear": "",
                    "testedproductionyear": "",
                    "alcoholstrength": "9.4%",
                    "module": "T5",
                    "assortment": "TSE",
                    "organic": "0",
                    "kosher": "0"
                },
                {
                    "nr": "140615",
                    "articleid": "508224",
                    "articletype": "1406",
                    "name": "Anderssons",
                    "name2": "",
                    "priceinclvat": "8.90",
                    "volumeml": null,
                    "priceperlitre": null,
                    "introduced": "2010-10-01",
                    "finaldelivery": " ",
                    "catgegory": "\u00c3\u2013l, Ljus lager",
                    "packaging": "Burk",
                    "captype": "",
                    "countryoforigin": "",
                    "countryoforiginlandname": "Sverige",
                    "producer": "Hellefors Bryggeri",
                    "provider": "Anderssons \u00c3\u2013l AB",
                    "productionyear": "",
                    "testedproductionyear": "",
                    "alcoholstrength": "5.2%",
                    "module": "",
                    "assortment": "FS",
                    "organic": "0",
                    "kosher": "0"
                },
                {
                    "nr": "140715",
                    "articleid": "675480",
                    "articletype": "1407",
                    "name": "Backyard Brew",
                    "name2": "The Lawn Mower",
                    "priceinclvat": "9.90",
                    "volumeml": null,
                    "priceperlitre": null,
                    "introduced": "2012-10-01",
                    "finaldelivery": " ",
                    "catgegory": "\u00c3\u2013l, Ljus lager",
                    "packaging": "Burk",
                    "captype": "",
                    "countryoforigin": "Hallands l\u00c3\u00a4n, Falkenbergs kommun",
                    "countryoforiginlandname": "Sverige",
                    "producer": "Carlsberg Sverige AB",
                    "provider": "Carlsberg Sverige AB",
                    "productionyear": "",
                    "testedproductionyear": "",
                    "alcoholstrength": "4.8%",
                    "module": "",
                    "assortment": "BS",
                    "organic": "0",
                    "kosher": "0"
                }, {
                "nr": "1001",
                "articleid": "190719",
                "articletype": "10",
                "name": "Vanlig Vodka",
                "name2": "",
                "priceinclvat": "195.00",
                "volumeml": null,
                "priceperlitre": null,
                "introduced": "2006-04-01",
                "finaldelivery": " ",
                "catgegory": "Okryddad sprit",
                "packaging": "Flaska",
                "captype": "Skruvkapsyl",
                "countryoforigin": "",
                "countryoforiginlandname": "Sverige",
                "producer": "Svensk Export Vodka AB",
                "provider": "Fondberg",
                "productionyear": "",
                "testedproductionyear": "",
                "alcoholstrength": "37.5%",
                "module": "",
                "assortment": "FS",
                "organic": "0",
                "kosher": "0"
            },{
                "nr": "1031701",
                "articleid": "678936",
                "articletype": "10317",
                "name": "The Macallan",
                "name2": "MacKillop's Choice",
                "priceinclvat": "1980.00",
                "volumeml": null,
                "priceperlitre": null,
                "introduced": "2012-09-01",
                "finaldelivery": " ",
                "catgegory": "Whisky, Malt",
                "packaging": "Flaska",
                "captype": "",
                "countryoforigin": "Skottland, Highlands, Speyside",
                "countryoforiginlandname": "Storbritannien",
                "producer": "Angus Dundee",
                "provider": "Philipson S\u00c3\u00b6derberg AB",
                "productionyear": "1990",
                "testedproductionyear": "",
                "alcoholstrength": "50.6%",
                "module": "",
                "assortment": "TSE",
                "organic": "0",
                "kosher": "0"
            }, {
                "nr": "1005401",
                "articleid": "733429",
                "articletype": "10054",
                "name": "Linkwood",
                "name2": "the Octave",
                "priceinclvat": "1159.00",
                "volumeml": null,
                "priceperlitre": null,
                "introduced": "2013-03-01",
                "finaldelivery": " ",
                "catgegory": "Whisky, Malt",
                "packaging": "Flaska",
                "captype": "",
                "countryoforigin": "Skottland, Highlands, Speyside",
                "countryoforiginlandname": "Storbritannien",
                "producer": "Duncan Taylor Scotch Whisky",
                "provider": "Clydesdale AB",
                "productionyear": "1989",
                "testedproductionyear": "",
                "alcoholstrength": "51.7%",
                "module": "",
                "assortment": "TSE",
                "organic": "0",
                "kosher": "0"
            },{
                "nr": "1034301",
                "articleid": "596562",
                "articletype": "10343",
                "name": "Domaine Boingn\u00c3\u00a8res",
                "name2": "Eau de Vie Folle Blanche",
                "priceinclvat": "857.00",
                "volumeml": null,
                "priceperlitre": null,
                "introduced": "2011-11-01",
                "finaldelivery": " ",
                "catgegory": "Brandy och Vinsprit, Vinsprit",
                "packaging": "Flaska",
                "captype": "Naturkork",
                "countryoforigin": "",
                "countryoforiginlandname": "Frankrike",
                "producer": "Domaine Boingn\u00c3\u00a8res",
                "provider": "BIN Vintage Import",
                "productionyear": "",
                "testedproductionyear": "",
                "alcoholstrength": "52%",
                "module": "",
                "assortment": "TSE",
                "organic": "0",
                "kosher": "0"
            }
            ],
   "stocks" :
            [
                {
                    "articleid": "889891",
                    "amount": "22"
                }, 
                {
                    "articleid": "889900",
                    "amount": "30"
                }, 
                {
                    "articleid": "889924",
                    "amount": "5"
                }, 
                {
                    "articleid": "889931",
                    "amount": "10"
                }, 
                {
                    "articleid": "889944",
                    "amount": "12"
                }, 
                {
                    "articleid": "785133",
                    "amount": "18"
                }, 
                {
                    "articleid": "890010",
                    "amount": "9"
                }, 
                {
                    "articleid": "890096",
                    "amount": "27"
                },
                {
                    "articleid": "890142",
                    "amount": "16"
                }, 
                {
                    "articleid": "890171",
                    "amount": "23"
                }, 
                {
                    "articleid": "890433",
                    "amount": "30"
                }, 
                {
                    "articleid": "890551",
                    "amount": "29"
                }, 
                {
                    "articleid": "890574",
                    "amount": "11"
                }, 
                {
                    "articleid": "865823",
                    "amount": "19"
                }, 
                {
                    "articleid": "730949",
                    "amount": "13"
                }, 
                {
                    "articleid": "734813",
                    "amount": "27"
                }, 
                {
                    "articleid": "735181",
                    "amount": "36"
                }, 
                {
                    "articleid": "723841",
                    "amount": "14"
                }, 
                {
                    "articleid": "508224",
                    "amount": "17"
                }, 
                {
                    "articleid": "675480",
                    "amount": "28"
                }

            ]
};